# Generated by Django 3.0.3 on 2020-02-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200211_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrelationship',
            name='child_hash',
        ),
        migrations.RemoveField(
            model_name='classrelationship',
            name='parent_hash',
        ),
        migrations.RemoveField(
            model_name='method',
            name='class_hash',
        ),
        migrations.RemoveField(
            model_name='method',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='methodparameter',
            name='method_hash',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='type',
            new_name='file_type',
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='ClassRelationship',
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.DeleteModel(
            name='MethodParameter',
        ),
    ]
